### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by thansen29** [thansen29/Stromble#1]
Front and back end authentication

- [x] Back end
  - [x] User model, user and session controllers
  - [x] User table built
  - [x] JBuilder for user and session

- [x] Front end 
  - [x] React/Redux Cycle
  - [x] Components

- [x] Home landing page
  - [x] Nav bar - Sign up and Log in
  - [x] Background image
  - [x] Modal Sign up form
  - [x] Styling

- [x] Log in form
  - [x] Demo login 
  - [x] Styling

**Comment by mashuDuek** [comment]
1. The modal's "Sign up for free" coloring is off by a little bit. 
2. The logo "stromble" needs to disappear upon opening the modal. 
3. Seems like your modal has too much padding. 
4. The signup button needs to be aligned with your input fields. 
5. The border of your input fields coloring is off. 
6. Missing the logout button to complete the auth feature.
