### ISSUE TITLE
Auth 2.0

### ISSUE THREAD

**Issue by thansen29** [thansen29/Stromble#2]
- [x] Sign up for free coloring
- [x] stromble logo dimming on modal open
- [x] modal padding
- [x] signup button aligned with input fields
- [x] border of input field color
- [x] logout button on dashboard
- [x] enhanced error handling on signup
- [x] added background text onto landing page

**Comment by mashuDuek** [comment]
1. The button to signup seems to have too much padding 
2. The modal to signup, its top border needs to be in line with the top nav bar, when handling errors it seems to expand towards the top (into the nav bar)
3. The modal itself seems to have too much padding
4. When highlighting an input field on your modals, they have a border radius on the input field, and that highlighting itself seems a little different 
5. They clear errors once you are selected on the input field, seems like you're clearing errors on component dismounting
- this last one is not a big deal, it'd be nice if you could fix it - i'd say maybe looking up different event handlers, maybe there's one that will be fired when you are selected in an input field. I think there may be one, called compositionstart (not too sure about that one, I looked at MDN docs quickly and saw it, not exactly sure if its what you need).

**Comment by mashuDuek** [comment]
Good to close.
