### ISSUE TITLE
Workouts

### ISSUE THREAD

**Issue by thansen29** [thansen29/Stromble#3]
- [x] Back end
  - [x] Workout model, controller
  - [x] workouts table, validations
  - [x] JBuilder - complete with partials

- [ ] Front end
  - [x] React/Redux Cycle
  - [ ] Components

- [ ] Create Workout Form
  - [ ] Error handling

- [ ]  View Workout
  - [ ] Edit Workout
  - [ ] Delete Workout

**Comment by mashuDuek** [comment]
Missing: edit, read, and delete functionalities.

**Comment by mashuDuek** [comment]
Missing some functionality, editing deleting etc. 
In the form to create a workout (run in my case) the background color of the dropdown "Run Type" is clear or something like that, and I can read other stuff through it. 
GREAT WORK.
